### PR TITLE
User page, checkout, and readme

### PR DESCRIPTION
**Pull request by MayankKumar10**
Adding User Page, Checkout, and Readme files

### CODE REVIEW

**Review by hsnice16 — APPROVED** [review]
Nice work, bro. I think, instead of copy-pasting the same repetitive code on different pages, you are using `iframe` to load the file. But I think there is some problem with the linking, check this 
image

And the same thing is coming `Page not found` on clicking the Account tab.

**Comment by MayankKumar10** [comment]
> Nice work, bro. I think, instead of copy-pasting the same repetitive code on different pages, you are using `iframe` to load the file. But I think there is some problem with the linking, check this image
> 
> And the same thing is coming `Page not found` on clicking the Account tab.

Live Link Shows The file which already has been merged, after merging this pull request they will not give this issue.

Thanks, Himanshu for the detailed PR Review

**Review by yash9263 — APPROVED** [review]

**Comment by yash9263** [comment]
I think 2s is a lot of time for transitioning it should be in between 200ms to 600ms should give a better transition effect.
as most values are 2s you can use CSS variables to declare this value it would be faster in checking which ones working

**Comment by MayankKumar10** [comment]
> I think 2s is a lot of time for transitioning it should be in between 200ms to 600ms should give a better transition effect. as most values are 2s you can use CSS variables to declare this value it would be faster in checking which ones working

Okay, I'll do that change. Thank's Yashwant for Pointing that out.

**Pull request merged**
